language: swift
install:
  - gem install cocoapods

stages:
  - name: lint
  - name: versioncheck
    if: tag =~ ^\d+\.\d+\.\d+$
  - name: deploy
    if: tag =~ ^\d+\.\d+\.\d+$


jobs:
  include:
    - stage: lint
      script:
        - pod lib lint
    - stage: versioncheck
      script:
        - ( [ "$TRAVIS_TAG" = $(./get_podspec_version.sh aBlinkingLabel.podspec) ] )
    - stage: deploy
      script:
        - pod trunk push --allow-warnings
