language: swift
install:
  - gem install cocoapods

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      script:
        - pod spec lint
    - stage: deploy
      script:
        - pod trunk push
