language: minimal

stages:
  - name: lint
  - name: deploy
    if: tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: lint
      os: osx
      language: swift
      install: gem install cocoapods
      script:
        - pod lib lint
        - echo $PWD
        - echo "hi $PWD"
        - echo "$TRAVIS_TAG"
        - ./get_podspec_version.sh aBlinkingLabel.podspec
    - stage: deploy
      os: osx
      language: swift
      install: gem install cocoapods
      script:
        - pod trunk push --allow-warnings
      after_failure:
        - echo "$TRAVIS_TAG"
        - ./get_podspec_version.sh aBlinkingLabel.podspec
