language: minimal

stages:
  - name: lint
  - name: deploy
    if: tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: lint
      os: osx
      language: swift
      install:
        - gem install cocoapods
      script:
        - pod lib lint
    - stage: deploy
      os: osx
      env: PODSPEC=aBlinkingLabel.podspec
      language: swift
      install:
        - gem install cocoapods
        - brew install jq
      before_script:
        - if [ $TRAVIS_TAG != $(pod ipc spec $PODSPEC | jq -r .version) ]; then echo "$PODSPEC s.version needs to match $TRAVIS_TAG"; exit 1; fi
      script:
        - pod trunk push --allow-warnings
