language: minimal

stages:
  - name: lint
  - name: deploy
    if: tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: lint
      os: osx
      language: swift
      install: gem install cocoapods
      script:
        - pod lib lint
    - stage: deploy
      os: osx
      language: swift
      env: PODSPEC=aBlinkingLabel.podspec
      install:
        - gem install cocoapods
        - brew install jq
      before_script:
        - ( [ $TRAVIS_TAG != $(pod ipc spec $PODSPEC | jq -r .version) ] ) && echo "$PODSPEC s.version needs to match $TRAVIS_TAG" && exit 1
      script:
        - pod trunk push --allow-warnings
