language: minimal

stages:
  - name: lint
  - name: deploy
    if: tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: lint
      os: osx
      language: swift
      install: gem install cocoapods
      script:
        - pod lib lint
    - stage: deploy
      os: osx
      language: swift
      install: gem install cocoapods
      script:
        - ( [ $TRAVIS_TAG = $(pod ipc spec aBlinkingLabel.podspec | jq -r .version) ] )
      deploy:
        - pod trunk push --allow-warnings
