language: minimal

stages:
  - name: prep
    if: env(PREP) = true and type = api
  - name: release
    if: env(RELEASE) = true and type = api

jobs:
  include:
    - stage: prep
      name: prepare for release
      os: osx
      language: swift
      env:
        - VERSION=4.0.0
      install:
        - brew install hub
      script:
        - ./run_prep.sh
    - stage: release
      name: release to cocoapods
      os: osx
      language: swift
      env:
        - VERSION=4.0.0
      install:
        - brew install hub
        - gem install cocoapods
      script:
        - ./run_release.sh
