language: swift
install:
  - gem install cocoapods

stages:
  - dockerversion
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      script:
        - pod spec lint
    - stage: deploy
      script:
        - pod trunk push --allow-warnings
    - stage: dockerversion 
      os: linux
      language: minimal
      script:
        - docker --version
