language: minimal

stages:
  - name: test hub
    if: env(HUB) = true and type = api
  - name: prep
    if: env(PREP) = true and type = api
  - name: release
    if: env(RELEASE) = true and type = api

jobs:
  include:
    - stage: test hub
      name: testing hub install
      os: osx
      language: minimal
      install:
        - wget ttps://github.com/github/hub/releases/download/v2.11.2/hub-darwin-amd64-2.11.2.tgz -O /tmp/hub-darwin-amd64-2.11.2.tgz
        - sudo tar -xvf /tmp/hub-darwin-amd64-2.11.2.tgz -C /usr/local/opt
        - sudo ln -s /usr/local/opt/hub-darwin-amd64-2.11.2/bin/hub /usr/local/bin/hub
      script:
        - hub version
    - stage: prep
      name: prepare for release
      os: osx
      language: swift
      env:
        - VERSION=4.0.0
      install:
        - brew install hub
      script:
        - ./run_prep.sh
    - stage: release
      name: release to cocoapods
      os: osx
      language: swift
      env:
        - VERSION=4.0.0
      install:
        - brew install hub
        - gem install cocoapods
      script:
        - ./run_release.sh
