language: swift
install:
  - gem install cocoapods

stages:
  - name: lint
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: lint
      script:
        - pod lib lint
    - stage: deploy
      script:
        - pod trunk push --allow-warnings
