language: objective-c
install:
- gem install cocoapods
script: true

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      script:
        - pod spec lint
    - stage: deploy
      script:
        - pod trunk push
